---
- hosts: localhost
  tasks:
    - name: icinga_downtime
      t_systems_mms.icinga_director.icinga_downtime:
        url: "blank"
        #use_proxy: "{{ icinga_use_proxy | default(omit) }}"
        #validate_certs: "{{ icinga_validate_certs | default(omit) }}"
        url_username: "testuser"
        url_password: ""
        force_basic_auth: True
        state: present
        object_name: "icinga director downtime"
        author: testuser
        comment: test
        fixed: True
        apply_to: host
        assign_filter: "'host.name'=blank"
        ranges:
          "tuesday": "00:00-24:00"
